name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u="chandan143" -p="chandan12"
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t chandan143/gitpush:$GITHUB_CHA
    - name: Docker push
      run: docker push chandan143/gitpush:$GITHUB_CHA
